# Checking tRNAs of E. coli for NAD-capping (potential)

In [1]:
import pandas as pd
import numpy as np

Import tRNA datasets/annotations.

In [ ]:
Ec_tRNAs_all = pd.read_csv('/Users/maikschauerte/Desktop/NAR_Revision/Phage_NAD-RNA_analysis/Updated_NAD-RNA_TSS_annotation/All_tRNA_Ec_promoters_dRNA.gff3', index_col=0, sep = '\t')
Ec_tRNAs_primary = pd.read_csv('/Users/maikschauerte/Desktop/NAR_Revision/Phage_NAD-RNA_analysis/Updated_NAD-RNA_TSS_annotation/Primary_tRNA_Ec_promoters_dRNA.gff3', index_col=0, sep='\t')
Ec_tRNAs_NAD_r1 = pd.read_csv('/Users/maikschauerte/Desktop/NAR_Revision/Phage_NAD-RNA_analysis/Updated_NAD-RNA_TSS_annotation/Host_tRNA_promoters_R1.gff3', index_col=0, sep = '\t')
Ec_tRNAs_NAD_r2 = pd.read_csv('/Users/maikschauerte/Desktop/NAR_Revision/Phage_NAD-RNA_analysis/Updated_NAD-RNA_TSS_annotation/Host_tRNA_promoters_R2.gff3', index_col=0, sep = '\t')
Ec_tRNAs_NAD_cons = pd.read_csv('/Users/maikschauerte/Desktop/NAR_Revision/Phage_NAD-RNA_analysis/Updated_NAD-RNA_TSS_annotation/Host_tRNA_promoters_consensus.gff3', index_col=0, sep = '\t')

In [5]:
# Example being primary tRNA promoters from E. coli

Ec_tRNAs_primary

,start,end,strand,ID,TSSType,UTR,AssociatedGene,Symbols,GeneTypes,Sequence
Genome,,,,,,,,,,
U00096.3,225450,225500,+,TSS:225500_f,Primary,Primary_0,b0203,alaV,tRNA,GCCTACCAAATTTGCACGGCAAATTTGAAGAGGTTTTAACTACATG...
U00096.3,228878,228928,+,TSS:228928_f,Primary,Primary_0,b0206,aspU,tRNA,AATTAAGCAGTAAGCCGGTCATAAAACCGGTGGTTGTAAAAGAATT...
U00096.3,236881,236931,+,TSS:236931_f,Primary,Primary_0,b0216,aspV,tRNA,AGGTCGAGGCAATCCGTAATATTCGCCTCGTTCCCAACGGAACACA...
U00096.3,262788,262838,+,TSS:262838_f,Primary,Primary_33,b0244,thrW,tRNA,GATTCACAAGGCCATTGACGCATCGCCCGGTTAGTTTTAACCTTGT...
U00096.3,564649,564699,+,TSS:564699_f,Primary,Primary_24,b0536,argU,tRNA,CCAGATCAAAAGCCATTGACTCAGCAAGGGTTGACCGTATAATTCA...
...,...,...,...,...,...,...,...,...,...,...
U00096.3,4392533,4392583,+,TSS:4392583_f,Primary,Primary_0,b4165,glyY,tRNA,TCGTTTCCCGCTCCAAAATTTGAAAGTGCTGTAAGGCACAGACCAC...
U00096.3,4496333,4496383,+,TSS:4496383_f,Primary,Primary_22,b4270,leuX,tRNA,CGAGCAAGCTGGCGCTTGCATGGTGGCGTGCGACAGGTATAATCCA...
U00096.3,4606165,4606215,-,TSS:4606165_r,Primary,Primary_0,b4368,leuV,tRNA,CCCCCCCCTCGCACCAAACGAGGCGATATCAAAAAAAGTAAGATGA...
U00096.3,4606286,4606336,-,TSS:4606286_r,Primary,Primary_0,b4369,leuP,tRNA,TCAAGTCCCCCCCCTCGCACCAAAAACCACGTTGATATTGCTCGCA...
U00096.3,4606434,4606484,-,TSS:4606434_r,Primary,Primary_33,b4370,leuQ,tRNA,TCGATAATTAACTATTGACGAAAAGCTGAAAACCACTAGAATGCGC...

How many have a +1A?

In [7]:
tRNAs1A = Ec_tRNAs_primary.loc[Ec_tRNAs_primary['Sequence'].str.endswith('A')].shape[0]
print('No. primary tRNA promoters with +1A: ' + str(tRNAs1A) + '. No. of primary tRNA promoters without +1A: ' + str(Ec_tRNAs_primary.shape[0]-tRNAs1A) + '. This makes a +1A ratio of ' + str(tRNAs1A/Ec_tRNAs_primary.shape[0]) + '.')

No. primary tRNA promoters with +1A: 16. No. of primary tRNA promoters without +1A: 45. This makes a +1A ratio of 0.26229508196721313.

Which ones mediate NAD-RNA capping according to our hits?
In the consensus, all promoters carry a +1A.

In [9]:
Ec_tRNAs_NAD_cons.loc[Ec_tRNAs_NAD_cons['Sequence'].str.endswith('A')].shape[0]

5

In [10]:
Ec_tRNAs_NAD_cons

,type,feature,start,end,fill1,strand,fill2,features,gene,Sequence
Chr,,,,,,,,,,
U00096.3,manual,TSS,1031717,1031767,.,-,.,ID=serT;Name=serT_TSS,serT,AAACAAATTAGGGGTTTACACGCCGCATCGGGATGTTTATAGTGCG...
U00096.3,manual,TSS,1992183,1992233,.,-,.,ID=glyW;Name=glyW_TSS,glyW,TGGTGAAAAATATCGTTGACTCATCGCGCCAGGTAAGTAGAATGCA...
U00096.3,manual,TSS,2520872,2520922,.,+,.,ID=valU;Name=valU_TSS,valU,CTTTAGAAAATGCGTTGACTCATTTTGAACTCTCCCTATAATGCGA...
U00096.3,manual,TSS,2947332,2947382,.,+,.,ID=metZ;Name=metZ_TSS,metZ,GGGTAAAAAAAAGGTTGCATGAAAACGCGAGCGGAGTATAGTGCGC...
U00096.3,manual,TSS,3318375,3318425,.,-,.,ID=metY;Name=metY_TSS,metY,ATTAGCAATAAACGTTGACAAAATGTGGCGTGGATCACTATAATGC...

In [ ]:
# Filter matching primary promoters from dRNA-seq

matchtRNAs = Ec_tRNAs_primary.loc[Ec_tRNAs_primary['Symbols'].isin(Ec_tRNAs_NAD_cons['gene'])] # which match comparably well
matchtRNAs

# Are they also annotated as +1A?
matchtRNAs.loc[matchtRNAs['Sequence'].str.endswith('A')].shape[0] # 4/5

4